### ISSUE TITLE
Projeots (typo) in section "Nossos projetos"

### ISSUE THREAD

**Issue by debora-pontotel** [uspgamedev/website#2]
![image](https://user-images.githubusercontent.com/70707475/194227032-d39425d9-5722-4b7f-9630-505c82a2107f.png)

**Comment by Kazuo256** [comment]
Parcialmente resolvido por #3

**Comment by Kazuo256** [comment]
A outra parte foi resolvida em 6690ee9e02c0af2d314a149fff15f19bc2da5163. Fechando!
